[flink][spark] fix incorrect first_row_id range in DataEvolution MergeInto (#7790)
Current first row id check in DataEvolutionPartialWriter maybe incorrect
because of special files i.e. Blob Files and Vector FIles, which may
cause:
```text
java.lang.AssertionError: assertion failed: Number of written records 2419 does not match expected number 244 for first row ID 19352.
```

This is because the blob file's record count override the normal file's
record count:
<img width="2244" height="280" alt="image"
src="https://github.com/user-attachments/assets/1338caea-46ee-4310-96e5-57c8336dc6c6"
/>

We should filter out special files when calculating first_row_id to
record_count mapping